language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

before_install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
